### PR TITLE
Fix: Issue #101 possible deadlock when running in JTP - threads below…

### PR DESCRIPTION
**Pull request by CoreRasurae**
… the FJSafeCyclicBarrier number of parties (refs #101)

There a bug since at least Aparapi 1.4.1 that may cause a deadlock when running in Java Thread Pool mode.
At the end of KernelRunner a FJSafeCyclicBarrier is used and is set to the group size, however if the number of threads able to run is less than the group size a deadlock could occur.
Also introduced a mechanism to monitor if pool threads of the ForkJoinPool die they are now expected to be logged.

### CODE REVIEW

**Comment by CoreRasurae** [comment]
@freemo This change may have increased the memory usage a tiny bit. I made the KernelRunner to use a thread per runner instance, because it was just a static pool for all instances. So if one had multiple threads calling kernel execute on different instances of the same class they would all execute in the same thread pool.

**Comment by freemo** [comment]
@CoreRasurae  That should be fine

**Comment by CoreRasurae** [comment]
@freemo A side effect of removing the FJSafeCyclicBarrier is that the JTP execution is now much faster.

**Comment by CoreRasurae** [comment]
@freemo On the other hand that could be exactly the problem of KernelRunner... Suppose you have ten threads calling kernel execute() each one with relevant group sizes, then they would all compete for the same ForkJoinPool and since some threads blocked inside the pool thread, ones from one kernel execution, others from another execution, they could eventually exhaust the threads available and deadlock in the barrier. However I'm not sure that is what happened, I don't know very well how a ForkJoinPool works.

**Comment by CoreRasurae** [comment]
@freemo From my side is ok to merge, you have nothing opposing...

**Comment by automenta** [comment]
now i remember: i encountered the problem with JTP and non-divisible # of threads problem too. i forget what i had to fix it with but it was fixible.  it was hard to believe it had that obvious design limitation.

**Comment by automenta** [comment]
... https://github.com/automenta/aparapi/blob/master/src/test/java/com/aparapi/runtime/MultithreadTest.java so i wrote this to make sure it wouldnt go unnoticed again

**Comment by freemo** [comment]
@automenta can you add that as a PR so i can test it before and after the fix?

**Comment by freemo** [comment]
@CoreRasurae Alright thanks, im reviewing, I'll let you know.

**Comment by automenta** [comment]
its one self contained file of junit tests - it isnt a fix so i would just copy and paste it

**Comment by freemo** [comment]
@CoreRasurae yea I know, I just wanted to make sure you got credit for the commit. I have no objection to adding it on your behalf though.

**Comment by freemo** [comment]
@automenta  yea I know, I just wanted to make sure you got credit for the commit. I have no objection to adding it on your behalf though.

**Comment by freemo** [comment]
@automenta your unit tests did not appear to trigger the bug in question. They all passed for me just fine locally both before and after i applied this PR. thanks though

**Pull request merged**
