### PR TITLE
feat(kernel): popcount and clz 

### PR DESCRIPTION
**Pull request by toonijn**
ISSUES CLOSED: #47

### CODE REVIEW

**Comment by freemo** [comment]
@toonijn  Thanks so much, let me know how you'd like to receive your $10 bounty, just send an email to syncleus@syncleus.com or directly to me at jeffrey.freeman@syncleus.com and i can either start an account for you or send out the bounty directly.

**Comment by freemo** [comment]
@toonijn By the way I'll accept this either way but if you can add an update to the change log as well as add your info tot he contributors file that would be helpful (otherwise ill add it myself when i get to it later).

**Comment by toonijn** [comment]
@freemo That should do it.

**Comment by freemo** [comment]
@toonijn and @shabanovd this was replaced by PR #76 which I have since approved and merged to master. It will be in the next release shortly.

**Pull request closed without merging**
