### PR TITLE
Fix: Fix kernel management inconsistencies regarding preferred device…

### PR DESCRIPTION
**Pull request by CoreRasurae**
…s management

Assuming invocation like:
Range range = device.createRange(...);
kernel.execute(range);

Fixes 4 issues...
Issue1 - If device instance is not the same device instance in 
              KernelPreferences.getPreferredDevice(Kernel kernel)
            the kernel wouldn't execute.

Issue2 - If device is not the first in the list of the KernelPreferences.preferredDevices then
             KernelPreferences.getPreferredDevice(Kernel kernel) will return another device
           the kernel wouldn't execute.

Issue3 - If boolean Kernel.isAllowedDevice(Device device) didn't allow the device that is returned by
             KernelPreferences.getPreferredDevice(Kernel kernel) but allowed another device(s) that are
             in the list of the KernelPreferences.preferredDevices 
           the kernel wouldn't execute.

Issue4 - KernelManager was storing the kernel preferences based on object hashCode() default implementation, which could result in collisions even with other kernel classes. It would also keep many kernel preferences, which make it difficult for client code to manage the preferences. In my opinion it is just over-engineering which complicates programming and code management with no added benefits. A KernelPreferences instance per Kernel class suffices. The user just specifies which devices are allowed for running a given kernel class, and then refines the selected device that actually executes the kernel with:
Range range = device.createRange(...);
kernel.execute(range);

### CODE REVIEW

**Comment by automenta** [comment]
rather than preferences or profiles i think of it in terms of available execution strategies.  the original api wasnt designed for the possibility of different execution options becoming available and unavailable -- maybe during mid-execution.  

the cpu thread pool runner guarantees aparapi will still be able to execute in any case, and installed devices may not even offer a speedup for a particular execution.  instead if the profiling could be relied on to intelligently choose the right execution method (with sufficient manual override configuration options) the end-user wouldnt need to even think about choosing a device.  they can just run their code, as the profiler builds a meta-profile of their code's requriements after repeated executions, then it becomes more clear when it should apply a device (ie. strategy).

one other feature i am imagining wrt to this is to offer some help to users for configuring their hardware, with popup links to driver downloads, and helping them understand why despite an attached device's raw compute power, the program or the drivers or the hardware setup somehow cant fully utilize it.  this could be some type of dashboard UI to manage the system and profiling data, and watch how it decides what resources to apply.  maybe it could be a plugin for jvisualvm

**Comment by automenta** [comment]
im imagining a much simpler api for the end-user. they just submit their kernel and any option job-specific parameters like loops/strides/synchronization/prioritization etc.  without any further knowledge of the hardware it begins running it with the fallback CPU threadpool.  this becomes visible in a manager UI.  if it hasnt done so already, aparapi scans the system for the hardware including any partially enabled or possibly enable-able devices or remote compute resources. then it begins collecting profiling data by experimentally executing some or all of the already submitted kernel work to measure the different strategies it discovered.  there may be an obvious choice in most cases, like if there is one CPU and one GPU and the GPU is consistently faster.    the profiling data would be temporary, gradually replaced with updated measurements and stored between sessions in their home directory, maybe fingerprinted by the bytecode to discern different types of workloads.  

a management GUI would essentially illustrate the match between device capabilities and the kernel's requirements in terms of latencies, cpu time, wall time, etc.

**Comment by CoreRasurae** [comment]
@automenta that makes sense, but if the kernels are called with different parameters and input loads, then the execution time can vary greatly and not give a good device performance hint. If aparapi tries to use a dummy kernel to benchmark the device, then it won't be truly effective, because performance on a given device depends on how well the kernel is programmed. Also a kernel made for GPU will be slow on a CPU and a kernel made for a CPU will be slow on a GPU. So it is not an easy task for aparapi, however the end user can have a dummy workload for the supported devices to have a performacne ratio per device, so that it becomes possible to do workload balancing across devices.

**Comment by CoreRasurae** [comment]
@freemo I've included the pom.xml change to fix hanging unit tests ( issue #122 )

**Comment by CoreRasurae** [comment]
@freemo Since this is reviewed and it is ready from my side, I am closing the PR.

**Comment by freemo** [comment]
while I like the direction @automenta is going as always with GPGPU stuff actually implementing it ina  way where it can truly optimize itself is a very difficult task

**Pull request merged**
