### PR TITLE
Update: Fully support OpenCL 1.2 barrier() - localBarrier(),  globalBarrier() and localGlobalBarrier() (refs 84)

### PR DESCRIPTION
**Pull request by CoreRasurae**
This PR will add full support for OpenCL 1.2  barrier() by de-deprecating globalBarrier() and introducing new localGlobalBarrier() corresponding respectively to OpenCL barrier(CLK_GLOBAL_MEM_FENCE) and barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE).

### CODE REVIEW

**Comment by CoreRasurae** [comment]
@freemo It looks like that, from my tests, NVIDIA always does barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE) implicitly no matter what barrier one selects - only barrier(CLK_LOCAL_MEM_FENCE) or only barrier(CLK_GLOBAL_MEM_FENCE). 
I don't know what AMD implementation does regarding this respect, will try later. However it is safer to allow full barrier() support in my opinion, because the NVIDIA or AMD  or another manufacturer behaviour may change with time and may not always do barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE) implicitly.

**Comment by CoreRasurae** [comment]
and the coverage report is not accurate.

**Comment by freemo** [comment]
@CoreRasurae For future reference when bumping the version in changelog its good practice to also bump it in the pom. But i always look for this and fix it after i accept the PR so no big deal.

No idea what is up with the CI skipping tests though.

**Comment by CoreRasurae** [comment]
Ok, I understand... completely forgot about updating the pom.xml, sorry.

**Pull request merged**
