### PR TITLE
Fix: Memory leak by not disposing kernel in unit tests of feature #79 plus code quality #81

### PR DESCRIPTION
**Pull request by CoreRasurae**
Feature #79:
Renames the unit test LocalArrayArgsIssue79Test to Issue79LocalArrayArgsTest, so that it is no longer skipped, plus removes the memory leak by ensuring the kernel is disposed at the end.

Feature #81:
Improves code quality by logically splitting long unit test class into two unit test classes, one with the base validations and another with the advanced validations. Also KernelRunner new methods are refactored to reduce code complexity by extracting methods, and reducing code duplication.

### CODE REVIEW

**Comment by freemo** [comment]
@CoreRasurae Am I correct in understanding that while this fixes a bug in the unit test that there was no bug in the core code? The changes to core code are mostly cosmetic?

**Comment by CoreRasurae** [comment]
Yes, the bug was in the unit tests. The changes I made were based on the code quality report from the previous build.

**Comment by CoreRasurae** [comment]
Strangely it seems that more tests are skipped now on CI environemt, don't know why. On my machine after rebasing to 1.6.0, I was getting the tests LocalArrayArgsIssue79Test also getting skipped, the 2 tests, then I renamed to Issue79LocalArrayArgsTests and they were no longer skipped. 
Now on my machine I have this:
[INFO] Running com.aparapi.runtime.Issue79LocalArrayArgsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.14 s - in com.aparapi.runtime.Issue79LocalArrayArgsTest
[INFO] Running com.aparapi.runtime.Issue81AtomicsSupportAdvTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.626 s - in com.aparapi.runtime.Issue81AtomicsSupportAdvTest
[INFO] Running com.aparapi.runtime.Issue81AtomicsSupportTest
[INFO] Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.584 s - in com.aparapi.runtime.Issue81AtomicsSupportTest


However on the CI environment they still keep being skipped, even after renaming, while now the Issue81 tests are also being skipped... after having split those tests into two classes, one with the base tests and the other with the more complete/advanced ones.

**Comment by CoreRasurae** [comment]
Let me make codacy completely happy it just complaining about a not so important thing, but I can make it happy in a second.

**Comment by freemo** [comment]
@CoreRasurae Yea im kinda clueless why certain tests are being skipped
myself. I tried looking into it before the last release. Since this PR
doesnt address a bug int he core code I'll still merge it when its ready
(let me know when its ready to merge) but i wont rush out a 1.6.1 release.

**Comment by CoreRasurae** [comment]
@freemo Sure, I will send a message when it is ready. I think there is no need for a 1.6.1 too, it is just minor things. BTW I sent you an email, this morning, to you work email address that I got from github, did you receive it?

**Comment by freemo** [comment]
@CoreRasurae I see that email now, responding...

**Comment by CoreRasurae** [comment]
@freemo I'm done with the changes. You can merge if you want to.

**Comment by freemo** [comment]
@CoreRasurae wonderful, thanks so much. I will review and merge. by the way you still dont have your commits linked up to your github account so you arent getting credit for them. Not sure if this is intentional but just wanted to let you know.

**Comment by freemo** [comment]
@CoreRasurae merged, thanks again!

**Pull request merged**
