### PR TITLE
Update: Add support for Local arguments in kernel functions (refs #79)

### PR DESCRIPTION
**Pull request by CoreRasurae**
Allows kernel functions to be called having as arguments arrays in local memory.
Such arguments are designated by @Local annotation or by the _$local$ suffix name.
As described in Issue 79 by the provided sample code.

A test case was added validate this implementation.

### CODE REVIEW

**Comment by freemo** [comment]
@CoreRasurae Changelog should be updated with all pull requests. Keep in mind for the future. I can add it to this PR when I approve though.

**Comment by freemo** [comment]
Aside from the code coverage being on the low side it looks pretty good. If we can increase the coverage a bit great, if not ill still approve.

**Comment by CoreRasurae** [comment]
The changelog is this:
[LocalArgs-79 fc70299] Update: Add support for Local arguments in kernel functions (refs #79)
 4 files changed, 311 insertions(+), 3 deletions(-)
 create mode 100644 src/test/java/com/aparapi/runtime/LocalArrayArgsIssue79Test.java

Yes,the code coverage is low because the unit test is not being called. It needs to be wired up.

**Comment by freemo** [comment]
@CoreRasurae Yea the test appears to be skipped. Any reason you hae it being skipped?

```
[INFO] Running com.aparapi.runtime.LocalArrayArgsIssue79Test
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in com.aparapi.runtime.LocalArrayArgsIssue79Test
```

**Comment by freemo** [comment]
@CoreRasurae Actually you dont appear to have it set to ignore. I'm a bit confused why/where it is getting skipped now, hmm.

**Comment by CoreRasurae** [comment]
I ran the test outside the aparapi maven build process and it was working. I don't see why it is being skipped...

**Comment by freemo** [comment]
@CoreRasurae Ahh so not intentional on your part. I will need to investigate that...

**Comment by CoreRasurae** [comment]
@freemo  An interesting fact... I based my test on BufferTransferTest which is also getting skipped. The difference I see to the remaining tests is the usage of @BeforeClass annotation, maybe it should just be @Before.
I'll check that.

**Comment by freemo** [comment]
@CoreRasurae That could be. We have a bunch of tests we do intentionally
skip so some of these may have gotten lost in the mix. It wasnt that long
ago i paid someone to go through and expand our test coverage so some
things got changed around.

**Comment by CoreRasurae** [comment]
Changelog:
[LocalArgs-79 72e319e] Update: Add support for Local arguments in kernel functions (refs #79) - improved unit test
 Author: Luis Mendes <luis.p.mendes@gmail.com>
 1 file changed, 23 insertions(+), 10 deletions(-)

**Comment by CoreRasurae** [comment]
@freemo The issue is with the Continuous Integration test environment. Maybe no OpenCL device is available.
On my machine I get:
[INFO] Running com.aparapi.runtime.LocalArrayArgsIssue79Test
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.889 s - in com.aparapi.runtime.LocalArrayArgsIssue79Test

**Comment by freemo** [comment]
@CoreRasura ahh yea there is no opencl device. But most tests should try to
fall back to running in java. But yea that may be it. Thats why I always
rerun the tests on a local machine as well. As long as it passes and the
code coverage is in the positive locally we should be good to go. I'll go
through it with a fine toothed comb.

**Comment by CoreRasurae** [comment]
@freemo Ok! Anyway this unit test will only produce correct code coverage if an OpenCL device is available, because the implementation code will only be exercised if the OpenCL source is generated. This also means that the unit test will only be doing useful testing if OpenCL source is generated and run on an OpenCL device. From the JTP standpoint there are no changes, since Java makes no use of the annotations employed in the test. There is no distinction in Java for the distinct OpenCL memory spaces.

**Comment by freemo** [comment]
@CoreRasurae Sorry I made a mistake in my last comment. Travis does in fact
run the code on opencl, it compiles opencl code. It simply runs it on the
cpu not gpu.

**Comment by CoreRasurae** [comment]
I see... then it should work. Here it runs happily both on CPU or GPU. It is being skipped for another reason, then.

**Comment by freemo** [comment]
thanks, I will investigate this

**Pull request merged**
