### PR TITLE
Revert "Fix and Update: Fix issue #62 and provide new API for kernel profiling under multithreading (refs #62)"

### PR DESCRIPTION
**Pull request by freemo**
this PR may have introduced bugs so testing a revert here.

### CODE REVIEW

**Comment by freemo** [comment]
@CoreRasurae so i am 95% sure that the bugs we talked about in your pr were introduced from that PR somehow... this PR reverts yours and it seems to pass everytime i run it, but master where your PR is merged fails often with similar errors

**Comment by CoreRasurae** [comment]
@freemo but, does it fails on other unit tests with deadlock?

**Comment by CoreRasurae** [comment]
@fremo I am able to reproduce the bug before the feature was merged at commit cd911b937c7804dac495f5fadd573fe1f2ac5a4f -  test: added another test showing out of scope error. 

With the attached test - 
[ProfileReportBackwardsCompatTest.java.txt](https://github.com/Syncleus/aparapi/files/1935359/ProfileReportBackwardsCompatTest.java.txt)

**Comment by CoreRasurae** [comment]
@freemo However if reverting to commit df12473c11bd9d7cdd08a64e2297071a218af88d - build(versioning): bumped snapshot version to 1.7, the deadlock no longer happens with the same test.

**Comment by CoreRasurae** [comment]
@freemo Not true, I was able to reproduce the deadlock even with the aparapi-1.6.0.jar release.

**Comment by CoreRasurae** [comment]
@freemo The problem is also reproducible with aparapi-1.4.1 release.

**Comment by freemo** [comment]
since bug was reproduced in 1.4.1 gonna close this

**Pull request closed without merging**
